test1: mergesort.c
	gcc -o test1 mergesort.c -Wall -Wextra -Wshadow -g -fsanitize=address,undefined

test2: power_of_2.c
	gcc -o test2 power_of_2.c #-Wall -Wextra -Wshadow -g -fsanitize=address,undefined

test3: bitcpy.c
	gcc -o test3 bitcpy.c -Wall -Wextra -Wshadow -g -fsanitize=address,undefined

clean:
	rm test1 test2 test3
